# Generated by Django 5.1.2 on 2024-11-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_opinion_opinion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='rate',
        ),
    ]
