# Generated by Django 5.1.1 on 2024-10-15 09:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_announcement_image_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
