# Generated by Django 5.1.1 on 2024-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_category_slug_announcement_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
