# Generated by Django 5.1.1 on 2024-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_profile_address_alter_profile_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
