# Generated by Django 5.1.2 on 2024-11-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_announcement_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
