# Generated by Django 5.1.2 on 2024-11-15 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile_first_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 8, 59, 23, 525818, tzinfo=datetime.timezone.utc)),
        ),
    ]
